services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test:
    build: .
    environment:
      - JWT_SECRET=03d2b1244f2371c1f110dede986c337282d2289dfacf59b5ff47825d0fffed55aa960221a6d8c0d5c8fc3bc1bbfebc286b6acbd7f79125d4a9e1c773860462de
      - PORT=3000
      - NODE_ENV=test npm test
      - POSTGRES_DB=testdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    command: npm test
    depends_on:
      - db

volumes:
  postgres-data:
